[build]
  base = "/"
  publish = "dist/"
  command  = "npx browserslist@latest --update-db && npm run build"
  functions = "my_functions/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
